name: Update PR Title
on:
    pull_request:
        types: [opened, edited, synchronize]

    permissions:
        pull-requests: write

jobs:
    update-pr:
        runs-on: ubuntu-latest
        steps:
            - name: PR 제목 업데이트
              uses: actions/github-script@v7
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      const prTitle = context.payload.pull_request.title;
                      const branchName = context.payload.pull_request.head.ref;

                      if (!prTitle.startsWith("[자동]")) {
                        await github.rest.pulls.update({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          pull_number: context.payload.pull_request.number,
                          title: `[자동] ${branchName} - ${prTitle}`,
                          body: "트윗 추가 페이지 구성"
                        });
                      }
